CREATE DATABASE SISTEMA;
USE SISTEMA;

CREATE TABLE CONTA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    MATRICULA VARCHAR(12),
    SENHA VARCHAR(20),
    PERFIL INT(4)
);

CREATE TABLE ESTUDANTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PERIODO_CURSO INT(10),
    PESSOA_ID INT(3),
    ORIENTADOR_ID INT(3),
    SUPERVISOR_ID INT(3),
    CONTA_ID INT(3),
    CURSO_ID INT(3)
);

CREATE TABLE ENDERECO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(255),
    BAIRRO VARCHAR(255),
    CEP VARCHAR(255),
    CIDADE VARCHAR(255),
    ESTADO VARCHAR(255)
);

CREATE TABLE PESSOA(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CPF VARCHAR(255) UNIQUE,
    RG VARCHAR(255) UNIQUE,
    ORGAO_EXPEDIDOR VARCHAR(255),
    TELEFONE VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    ENDERECO_ID INT(3),
    CONSTRAINT FK_ENDERECO_PESSOA FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID)
);

CREATE TABLE ORIENTADOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    PESSOA_ID INT(3),
    CONSTRAINT FK_PESSOA_ORIENTADOR FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA (ID)
);

CREATE TABLE CURSO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CARGA_HORARIA INT(10)
);

CREATE TABLE CONCEDENTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CNPJ VARCHAR(50),
    RAZAO_SOCIAL VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(14),
    ENDERECO_ID INT(3),
    CONSTRAINT FK_CONCEDENTE_ENDERECO FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ID)
);

CREATE TABLE SUPERVISOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CARGO VARCHAR(255),
	EMAIL VARCHAR(255),
    TELEFONE VARCHAR(255),
    CONCEDENTE_ID INT(3),
    CONSTRAINT FK_SUPERVISOR_CONCEDENTE FOREIGN KEY (CONCEDENTE_ID) REFERENCES CONCEDENTE (ID)
);

CREATE TABLE REPRESENTANTE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CARGO VARCHAR(255),
    PESSOA_ID INT(3),
    CONCEDENTE_ID INT(3),
    CONSTRAINT FK_REPRESENTANTE_PESSOA FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA (ID),
    CONSTRAINT FK_REPRESENTANTE_CONCEDENTE FOREIGN KEY (CONCEDENTE_ID) REFERENCES CONCEDENTE (ID)
);

CREATE TABLE ESTAGIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INICIO VARCHAR(255),
    DATA_FIM VARCHAR(255),
    HORA_ENTRADA VARCHAR(255),
    HORA_SAIDA VARCHAR(255),
    DURACAO VARCHAR(255),
    ESTUDANTE_ID INT(3),
    CONCEDENTE_ID INT(3),
    CONSTRAINT FK_ESTAGIO_ESTUDANTE FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE (ID),
    CONSTRAINT FK_ESTAGIO_CONCEDENTE FOREIGN KEY (CONCEDENTE_ID) REFERENCES CONCEDENTE (ID)
);

INSERT INTO CONTA VALUES (1, 'FRANCISCO MOZAR', '202114010001', 'aluno', 4);

INSERT INTO ESTUDANTE(ID, CONTA_ID) VALUES (1, 1);

INSERT INTO CURSO(NOME, CARGA_HORARIA) VALUES 
('MEDIO INTEGRADO - TECNICO EM INFORMATICA', 400),
('MEDIO INTEGRADO - TECNICO EM EDIFICAÇÕES', 400),
('MEDIO INTEGRADO - TECNICO EM AGROPECUARIA', 400)
;

INSERT INTO PESSOA(NOME, CPF, RG, ORGAO_EXPEDIDOR, TELEFONE, EMAIL) VALUES 
('HERALDO LIMA','13567364756','28374645','SDS-PE','87991726354','heraldo@orientador'),
('PEDRO LEMOS','15346573645','12635465','SDS-PE','87991028374','pedro@orientador'),
('FRANCISCO JUNIOR','12346578967','46577364','SDS-PE','87991027364','francisco@orientador'),
('PEDRO NUNES', '47589609837','284756423','SDS-PE','87991263457','pedro@representante'),
('PAULO DOS SANTOS', '92746573845','82764565','SDS-PE','87991756478','paulo@representante'),
('JOAQUIM RODRIGUES', '37456784957','73567840','SDS-PE','87991085764','joaquim@representante')
;

INSERT INTO ORIENTADOR(PESSOA_ID) VALUES
(1),
(2),
(3)
;

INSERT INTO ENDERECO(LOGRADOURO, NUMERO, BAIRRO, CEP, CIDADE, ESTADO) VALUES
('RUA ANTONIO JOAQUIM NETO',20,'CENTRO','56190000','TERRA NOVA','PE'),
('RUA MAJOR RAIMUNDO DE SA',50,'CENTRO','56190000','TERRA NOVA','PE'),
('RUA JOAO ANTONIO DOS SANTOS',10,'CENTRO','56190000','TERRA NOVA','PE')
;

INSERT INTO CONCEDENTE(NOME, CNPJ, RAZAO_SOCIAL, EMAIL, TELEFONE, ENDERECO_ID) VALUES
('FORTTI INTERNATIONAL', '04.057.696/0001-43', 'EMPRESA DE PEQUENO PORTE', 
'fortti@empresa', '87991736455', 1),
('IMPACT INTERNATIONAL', '82.432.711/0001-08', 'EMPRESA DE PEQUENO PORTE', 
'fortti@empresa', '87991837466', 2),
('BALANCE INTERNARIONAL', '84.038.861/0001-59', 'EMPRESA DE PEQUENO PORTE', 
'fortti@empresa', '87991356478', 3)
;

INSERT INTO SUPERVISOR(NOME, CARGO, EMAIL, TELEFONE, CONCEDENTE_ID) VALUES 
('ANTONIO DOS SANTOS', 'PROGRAMADOR', 'antonio@supervisor', '87991736457', 1),
('JOAO PAULO RODRIGUES', 'MESTRE DE OBRA', 'jose@supervisor','87991236457', 2),
('JOSE PEREIRA GOMES', 'CHEFE', 'jose@supervisor', '87991236457', 3)
;

INSERT INTO REPRESENTANTE(CARGO, PESSOA_ID, CONCEDENTE_ID) VALUES
('GERENTE', 4, 1),
('GERENTE', 5, 2),
('GERENTE', 6, 3)
;